services:
  db:
    image: postgres:13
    container_name: my-postgres-container
    environment:
      POSTGRES_DB: tcd_db
      POSTGRES_USER: transcendence
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: ./server/
    container_name: backend
    command: sh -c "python manage.py makemigrations api && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./server:/app
    working_dir: /app/tcd_back
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_NAME: tcd_db
      DATABASE_USER: transcendence
      DATABASE_PASSWORD: 123456
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379

  nginx:
    build:
      context: ./client
    container_name: nginx
    ports:
      - "8080:80"
      - "4443:443"
    volumes:
      - ./client/ssl:/etc/nginx/ssl

  redis:
    image: "redis:alpine"
    container_name: my-redis-container
    ports:
      - "6380:6379"

volumes:
  postgres_data: