# Generated by Django 5.1.1 on 2024-10-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match_Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('game', models.CharField(max_length=20)),
                ('player1_id', models.IntegerField()),
                ('player2_id', models.IntegerField()),
                ('match_type', models.CharField(max_length=20)),
                ('player1_score', models.IntegerField()),
                ('player2_score', models.IntegerField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
