# Generated by Django 5.1.1 on 2024-10-12 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_match_record_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match_record',
            name='player1_id',
        ),
        migrations.RemoveField(
            model_name='match_record',
            name='player2_id',
        ),
        migrations.AddField(
            model_name='match_record',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player1_matches', to='api.user'),
        ),
        migrations.AddField(
            model_name='match_record',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player2_matches', to='api.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, to='api.user'),
        ),
    ]
