# Generated by Django 5.1.1 on 2024-10-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_match_record_player1_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_record',
            name='fastest_ball_speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match_record',
            name='player1_ball_touch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match_record',
            name='player1_consec_touch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match_record',
            name='player2_ball_touch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match_record',
            name='player2_consec_touch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='blocked_friends',
            field=models.ManyToManyField(blank=True, to='api.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='pong_ball',
            field=models.IntegerField(default=9),
        ),
        migrations.AddField(
            model_name='user',
            name='pong_slider',
            field=models.IntegerField(default=9),
        ),
        migrations.AddField(
            model_name='user',
            name='tic_tac_toe_background',
            field=models.IntegerField(default=9),
        ),
        migrations.AddField(
            model_name='user',
            name='tic_tac_toe_sign',
            field=models.IntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='match_record',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='match_record',
            name='player1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match_record',
            name='player2_score',
            field=models.IntegerField(default=0),
        ),
    ]
